In [ ]:
# ********************************
#         READING FILES
# ********************************

In [15]:
# 1. Read CSV File

import pandas as pd
df = pd.read_csv(r"C:\Users\boyal\OneDrive\Customer_Churn_Analysis\01_Data\raw_data.csv")

In [ ]:
# Important Options

# pd.read_csv("data.csv", nrows=5)        # first 5 rows
# pd.read_csv("data.csv", usecols=["Name","Sales"])  # specific columns
# pd.read_csv("data.csv", skiprows=2)    # skip rows

In [16]:
df.head()

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,CUST0000000001,2022-12-12 12:53:58.199463,43,Female,55085.25,college,married,1,2,two_year,...,1,1,9.0,0.0,0,0,109.63,16,NaN,0
1,CUST0000000002,2022-01-13 12:53:58.199973,18,Male,60786.11,master,married,1,22,one_year,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
2,CUST0000000003,2023-09-04 12:53:58.199985,38,Female,73184.32,high_school,widowed,0,3,two_year,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
3,CUST0000000004,2022-06-27 12:53:58.199992,44,Male,40923.78,high_school,married,1,6,two_year,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
4,CUST0000000005,2022-12-08 12:53:58.199999,45,Female,36400.94,bachelor,single,0,9,two_year,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0

In [17]:
df.shape

(1000000, 32)

In [18]:
df.columns

Index(['customer_id', 'signup_date', 'age', 'gender', 'annual_income',
       'education', 'marital_status', 'dependents', 'tenure', 'contract',
       'payment_method', 'paperless_billing', 'senior_citizen',
       'monthlycharges', 'totalcharges', 'num_services', 'has_phone_service',
       'has_internet_service', 'has_online_security', 'has_online_backup',
       'has_device_protection', 'has_tech_support', 'has_streaming_tv',
       'has_streaming_movies', 'customer_satisfaction', 'num_complaints',
       'num_service_calls', 'late_payments', 'avg_monthly_gb',
       'days_since_last_interaction', 'credit_score', 'churn'],
      dtype='object')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   customer_id                  1000000 non-null  object
 1   signup_date                  1000000 non-null  object
 2   age                          1000000 non-null  int64
 3   gender                       1000000 non-null  object
 4   annual_income                970041 non-null   float64
 5   education                    1000000 non-null  object
 6   marital_status               1000000 non-null  object
 7   dependents                   1000000 non-null  int64
 8   tenure                       1000000 non-null  int64
 9   contract                     1000000 non-null  object
 10  payment_method               1000000 non-null  object
 11  paperless_billing            1000000 non-null  object
 12  senior_citizen               1000000 non-null  int64
 13  monthlycharges               1000000 non-null  float64
 14  totalcharges                 1000000 non-null  float64
 15  num_services                 1000000 non-null  int64
 16  has_phone_service            1000000 non-null  int64
 17  has_internet_service         1000000 non-null  int64
 18  has_online_security          1000000 non-null  int64
 19  has_online_backup            1000000 non-null  int64
 20  has_device_protection        1000000 non-null  int64
 21  has_tech_support             1000000 non-null  int64
 22  has_streaming_tv             1000000 non-null  int64
 23  has_streaming_movies         1000000 non-null  int64
 24  customer_satisfaction        980079 non-null   float64
 25  num_complaints               970094 non-null   float64
 26  num_service_calls            1000000 non-null  int64
 27  late_payments                1000000 non-null  int64
 28  avg_monthly_gb               949988 non-null   float64
 29  days_since_last_interaction  1000000 non-null  int64
 30  credit_score                 959605 non-null   float64
 31  churn                        1000000 non-null  int64
dtypes: float64(7), int64(17), object(8)
memory usage: 244.1+ MB

In [24]:
df.describe()

,age,annual_income,dependents,tenure,senior_citizen,monthlycharges,totalcharges,num_services,has_phone_service,has_internet_service,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
count,1000000.000000,970041.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.00000,1000000.000000,980079.000000,970094.000000,1000000.000000,1000000.000000,949988.000000,1000000.000000,959605.000000,1000000.000000
mean,44.724603,58788.311936,0.799831,22.381923,0.199511,86.443701,1837.321438,2.563721,0.769551,0.849742,...,0.59999,0.549086,6.159110,0.701667,1.760248,0.400969,39.095179,44.494191,678.562134,0.099227
std,14.479468,37137.433079,0.893654,20.073341,0.399633,27.592430,1803.721634,1.412330,0.421120,0.357324,...,0.48990,0.497585,2.328287,0.838148,1.485677,0.633289,43.852564,44.922587,87.642951,0.298967
min,18.000000,20000.000000,0.000000,1.000000,0.000000,20.000000,16.300000,1.000000,0.000000,0.000000,...,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,300.000000,0.000000
25%,34.000000,32712.560000,0.000000,6.000000,0.000000,70.490000,484.530000,1.000000,1.000000,1.000000,...,0.00000,0.000000,4.000000,0.000000,1.000000,0.000000,12.840000,12.000000,619.000000,0.000000
50%,44.000000,48954.600000,1.000000,16.000000,0.000000,85.480000,1249.750000,2.000000,1.000000,1.000000,...,1.00000,1.000000,7.000000,1.000000,1.000000,0.000000,27.770000,31.000000,680.000000,0.000000
75%,55.000000,73475.130000,1.000000,33.000000,0.000000,100.680000,2617.660000,3.000000,1.000000,1.000000,...,1.00000,1.000000,8.000000,1.000000,3.000000,1.000000,51.230000,62.000000,740.000000,0.000000
max,90.000000,250000.000000,5.000000,72.000000,1.000000,854.956730,16252.861508,6.000000,1.000000,1.000000,...,1.00000,1.000000,9.000000,7.000000,12.000000,5.000000,557.824023,365.000000,850.000000,1.000000

In [ ]:
# 2. Read Excel File

In [27]:
df2 = pd.read_excel(r"C:\Users\boyal\Downloads\advanced_conditional_1000.xlsx")

In [ ]:
# Multiple sheets:
# df = pd.read_excel("data.xlsx", sheet_name="Sheet1")

In [28]:
df2

,ID,Name,Dept,Region,Salary,Bonus,Marks,Attendance,JoinDate,Age,Experience,Rating,Status,Project,Manager
0,1001,Divya,IT,West,93570,5970,32,97,2021-10-19,42,14,4,Inactive,A,M3
1,1002,Arun,HR,South,49724,4431,75,51,2018-03-09,23,12,2,Active,B,M4
2,1003,Sara,Finance,South,64822,3225,59,70,2019-06-21,38,20,5,Inactive,B,M2
3,1004,Meena,HR,North,27120,4943,77,68,2022-05-30,31,15,5,Inactive,A,M3
4,1005,John,IT,North,55043,5579,79,90,2019-07-07,45,1,4,Inactive,D,M2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1996,John,Sales,South,59404,2133,94,76,2018-06-26,44,11,2,Active,B,M2
996,1997,Meena,IT,North,41120,1671,59,96,2018-03-28,37,17,2,Inactive,D,M1
997,1998,Sara,Sales,West,55236,1407,79,66,2022-12-17,31,14,1,Active,B,M1
998,1999,Divya,Finance,North,43436,8209,54,94,2018-11-16,37,8,5,Inactive,D,M1
999,2000,Teja,IT,South,33999,2098,40,54,2018-05-06,27,18,2,Inactive,C,M4

In [29]:
df.head(5)

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,CUST0000000001,2022-12-12 12:53:58.199463,43,Female,55085.25,college,married,1,2,two_year,...,1,1,9.0,0.0,0,0,109.63,16,NaN,0
1,CUST0000000002,2022-01-13 12:53:58.199973,18,Male,60786.11,master,married,1,22,one_year,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
2,CUST0000000003,2023-09-04 12:53:58.199985,38,Female,73184.32,high_school,widowed,0,3,two_year,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
3,CUST0000000004,2022-06-27 12:53:58.199992,44,Male,40923.78,high_school,married,1,6,two_year,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
4,CUST0000000005,2022-12-08 12:53:58.199999,45,Female,36400.94,bachelor,single,0,9,two_year,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0

In [31]:
df2.tail(3)

,ID,Name,Dept,Region,Salary,Bonus,Marks,Attendance,JoinDate,Age,Experience,Rating,Status,Project,Manager
997,1998,Sara,Sales,West,55236,1407,79,66,2022-12-17,31,14,1,Active,B,M1
998,1999,Divya,Finance,North,43436,8209,54,94,2018-11-16,37,8,5,Inactive,D,M1
999,2000,Teja,IT,South,33999,2098,40,54,2018-05-06,27,18,2,Inactive,C,M4

In [32]:
df2.shape

(1000, 15)

In [34]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1000 non-null   int64
 1   Name        1000 non-null   object
 2   Dept        1000 non-null   object
 3   Region      1000 non-null   object
 4   Salary      1000 non-null   int64
 5   Bonus       1000 non-null   int64
 6   Marks       1000 non-null   int64
 7   Attendance  1000 non-null   int64
 8   JoinDate    1000 non-null   datetime64[ns]
 9   Age         1000 non-null   int64
 10  Experience  1000 non-null   int64
 11  Rating      1000 non-null   int64
 12  Status      1000 non-null   object
 13  Project     1000 non-null   object
 14  Manager     1000 non-null   object
dtypes: datetime64[ns](1), int64(8), object(6)
memory usage: 117.3+ KB

In [36]:
df2.describe()

,ID,Salary,Bonus,Marks,Attendance,JoinDate,Age,Experience,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000.000000
mean,1500.500000,60186.065000,5514.683000,64.145000,74.957000,2020-09-19 03:53:16.800000256,33.181000,9.656000,2.919000
min,1001.000000,20010.000000,1012.000000,30.000000,50.000000,2018-01-01 00:00:00,21.000000,0.000000,1.000000
25%,1250.750000,40257.000000,3246.750000,47.000000,62.000000,2019-05-12 18:00:00,27.000000,4.000000,2.000000
50%,1500.500000,60239.500000,5510.000000,63.000000,75.000000,2020-09-10 00:00:00,33.000000,9.000000,3.000000
75%,1750.250000,79708.250000,7720.000000,82.000000,88.000000,2022-02-11 00:00:00,39.250000,15.000000,4.000000
max,2000.000000,99868.000000,9990.000000,100.000000,100.000000,2023-06-22 00:00:00,45.000000,20.000000,5.000000
std,288.819436,22847.121848,2607.147386,19.955054,15.026808,NaN,7.281157,6.189505,1.400143

In [ ]:
# 3. Read Text File
# df = pd.read_csv("data.txt", delimiter="\t")

In [ ]:
# 4. Read JSON File
# df = pd.read_json("data.json")