In [ ]:
# **************************************************************
#            Exploratory Data Analysis (EDA)
# **************************************************************

In [1]:
import pandas as pd

data = {
    "Order_ID": [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012],
    "Customer_Name": ["john","alice","bob","alice","david","eve","frank","john","grace","helen","ian","john"],
    "City": ["delhi","mumbai","delhi","mumbai","chennai","chennai","chennai","delhi","chennai","mumbai","delhi","delhi"],
    "Product": ["laptop","phone","tablet","laptop","phone","tablet","laptop","laptop","phone","tablet","laptop","phone"],
    "Quantity": [1,2,1,1,3,1,2,1,2,2,1,2],
    "Price": [50000,20000,15000,50000,22000,15000,52000,50000,22000,16000,51000,21000],
    "Order_Date": [
        "2023-01-01","2023-02-01","2023-03-01","2023-04-01",
        "2023-05-01","2023-06-01","2023-07-01","2023-08-01",
        "2023-09-01","2023-10-01","2023-11-01","2023-12-01"
    ]
}

df = pd.DataFrame(data)
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [2]:
df

    Order_ID Customer_Name     City Product  Quantity  Price Order_Date
0       1001          john    delhi  laptop         1  50000 2023-01-01
1       1002         alice   mumbai   phone         2  20000 2023-02-01
2       1003           bob    delhi  tablet         1  15000 2023-03-01
3       1004         alice   mumbai  laptop         1  50000 2023-04-01
4       1005         david  chennai   phone         3  22000 2023-05-01
5       1006           eve  chennai  tablet         1  15000 2023-06-01
6       1007         frank  chennai  laptop         2  52000 2023-07-01
7       1008          john    delhi  laptop         1  50000 2023-08-01
8       1009         grace  chennai   phone         2  22000 2023-09-01
9       1010         helen   mumbai  tablet         2  16000 2023-10-01
10      1011           ian    delhi  laptop         1  51000 2023-11-01
11      1012          john    delhi   phone         2  21000 2023-12-01

In [ ]:
# ===================================================
#         NOW: EDA (What + How + Why)
# ===================================================

In [ ]:
# ---------------------------------------
#     STEP 1: Basic Understanding
# ---------------------------------------

In [ ]:
# Number of rows → size of data
# Data types → correct or not
# Stats → mean, min, max

In [3]:
df.shape

(12, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       12 non-null     int64
 1   Customer_Name  12 non-null     object
 2   City           12 non-null     object
 3   Product        12 non-null     object
 4   Quantity       12 non-null     int64
 5   Price          12 non-null     int64
 6   Order_Date     12 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 804.0+ bytes

In [5]:
df.describe()

          Order_ID   Quantity        Price           Order_Date
count    12.000000  12.000000     12.00000                   12
mean   1006.500000   1.583333  32000.00000  2023-06-16 12:00:00
min    1001.000000   1.000000  15000.00000  2023-01-01 00:00:00
25%    1003.750000   1.000000  19000.00000  2023-03-24 06:00:00
50%    1006.500000   1.500000  22000.00000  2023-06-16 00:00:00
75%    1009.250000   2.000000  50000.00000  2023-09-08 12:00:00
max    1012.000000   3.000000  52000.00000  2023-12-01 00:00:00
std       3.605551   0.668558  16602.29995                  NaN

In [ ]:
# -----------------------------------------------
#         STEP 2: Add Business Column
# -----------------------------------------------

In [7]:
df["Total_Amount"] = df["Quantity"] * df["Price"]
df

,Order_ID,Customer_Name,City,Product,Quantity,Price,Order_Date,Total_Amount
0,1001,john,delhi,laptop,1,50000,2023-01-01,50000
1,1002,alice,mumbai,phone,2,20000,2023-02-01,40000
2,1003,bob,delhi,tablet,1,15000,2023-03-01,15000
3,1004,alice,mumbai,laptop,1,50000,2023-04-01,50000
4,1005,david,chennai,phone,3,22000,2023-05-01,66000
5,1006,eve,chennai,tablet,1,15000,2023-06-01,15000
6,1007,frank,chennai,laptop,2,52000,2023-07-01,104000
7,1008,john,delhi,laptop,1,50000,2023-08-01,50000
8,1009,grace,chennai,phone,2,22000,2023-09-01,44000
9,1010,helen,mumbai,tablet,2,16000,2023-10-01,32000
10,1011,ian,delhi,laptop,1,51000,2023-11-01,51000
11,1012,john,delhi,phone,2,21000,2023-12-01,42000

In [ ]:
# -----------------------------------------------
#         STEP 3: Total Revenue
# -----------------------------------------------

In [ ]:
# Insight: Total business revenue

df["Total_Amount"].sum()

np.int64(559000)

In [ ]:
# -----------------------------------------------
#       STEP 4: Top Selling Product
# -----------------------------------------------

In [ ]:
# Insight:
# Which product sells most

df.groupby("Product")["Quantity"].sum().sort_values(ascending=False).reset_index()

  Product  Quantity
0   phone         9
1  laptop         6
2  tablet         4

In [ ]:
# -----------------------------------------------
#       STEP 5: Highest Revenue Product
# -----------------------------------------------

In [ ]:
# Insight:
# Which product earns most money

df.groupby("Product")["Total_Amount"].sum().sort_values(ascending=False).reset_index()

  Product  Total_Amount
0  laptop        305000
1   phone        192000
2  tablet         62000

In [ ]:
# -----------------------------------------------
#     STEP 6: Revenue by City
# -----------------------------------------------

In [ ]:
# Insight:
# Best performing city

df.groupby("City")["Total_Amount"].sum().reset_index()

      City  Total_Amount
0  chennai        229000
1    delhi        208000
2   mumbai        122000

In [ ]:
# -----------------------------------------------
#   STEP 7: Top Customers
# -----------------------------------------------

In [23]:
# Insight:
# Most frequent buyers

df["Customer_Name"].value_counts().reset_index(name="Number_of_purchases")

  Customer_Name  Number_of_purchases
0          john                    3
1         alice                    2
2           bob                    1
3         david                    1
4           eve                    1
5         frank                    1
6         grace                    1
7         helen                    1
8           ian                    1

In [ ]:
# -----------------------------------------------
#   STEP 8: Highest Order Value
# -----------------------------------------------

In [37]:
# Insight:
# Biggest single order

df.sort_values(by="Total_Amount", ascending=False).head(1)

,Order_ID,Customer_Name,City,Product,Quantity,Price,Order_Date,Total_Amount
6,1007,frank,chennai,laptop,2,52000,2023-07-01,104000

In [38]:
df.loc[df["Total_Amount"].idxmax()]

Order_ID                        1007
Customer_Name                  frank
City                         chennai
Product                       laptop
Quantity                           2
Price                          52000
Order_Date       2023-07-01 00:00:00
Total_Amount                  104000
Name: 6, dtype: object

In [ ]:
# -----------------------------------------------
#   STEP 9: Monthly Sales Trend
# -----------------------------------------------

In [33]:
# Insight:
# Which months have high sales

df.groupby("Order_Date")["Total_Amount"].sum().reset_index()

   Order_Date  Total_Amount
0  2023-01-01         50000
1  2023-02-01         40000
2  2023-03-01         15000
3  2023-04-01         50000
4  2023-05-01         66000
5  2023-06-01         15000
6  2023-07-01        104000
7  2023-08-01         50000
8  2023-09-01         44000
9  2023-10-01         32000
10 2023-11-01         51000
11 2023-12-01         42000

In [ ]:
# -----------------------------------------------
#  STEP 10: Average Order Value
# -----------------------------------------------

In [ ]:
# Business metric: AOV (Average Order Value)

df["Total_Amount"].mean().round()

np.float64(46583.0)