In [ ]:
# ***************************
#     Pandas Equivalent
# ***************************

In [1]:
import pandas as pd

data = {
    "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Smartwatch"]
}

df = pd.DataFrame(data)

In [2]:
# 1. LIKE '%Lap%' (contains)
df[df["Product"].str.contains("Lap")]

  Product
0  Laptop

In [3]:
# 2. LIKE 'Lap%' (starts with)
df[df["Product"].str.startswith("Lap")]

  Product
0  Laptop

In [5]:
# 3. LIKE '%one' (ends with)
df[df["Product"].str.endswith("ones")]

      Product
3  Headphones

In [6]:
# 4. Case Insensitive
df[df["Product"].str.contains("lap", case=False)]

  Product
0  Laptop

In [7]:
# 5. Multiple Patterns
df[df["Product"].str.contains("Lap|Mob")]

  Product
0  Laptop
1  Mobile